In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data_for_dash_1.csv")
df.head().T

                            0           1         2           3           4
id                          1           2         3           4           5
type                    Konut       Konut     Konut       Konut       Konut
sub_type             Rezidans       Daire     Daire    Rezidans    Rezidans
start_date           12/10/18    02/13/19  10/09/18    09/10/18    12/10/18
end_date             01/09/19    02/27/19  11/08/18    10/10/18    01/09/19
listing_type                2           1         1           1           1
tom                        30          14        30          30          30
building_age                0           0         0           3           0
total_floor_count          21          21         1          21          21
floor_no                    2          20         1          20           2
room_count                  3           1         3           7           3
size                     90.0        43.0      85.0       450.0        90.0
heating_type          Fancoil     Fancoil   Fancoil     Fancoil     Fancoil
price                  8750.0   1225000.0  387500.0  81250000.0   3625000.0
price_currency            TRY         TRY       TRY         TRY         TRY
city                 İstanbul    İstanbul  Tekirdağ    İstanbul    İstanbul
district               Kartal      Kartal     Çorlu    Beşiktaş      Kartal
neighborhood       Kordonboyu  Kordonboyu  Reşadiye      Levent  Kordonboyu

In [3]:
df["type"].unique()

array(['Konut'], dtype=object)

In [4]:
df["type"] = df["type"].map({
    "Konut" : "Жилье"
})

In [5]:
df["sub_type"].unique()

array(['Rezidans', 'Daire', 'Villa', 'Müstakil Ev', 'Kooperatif',
       'Yazlık', 'Komple Bina', 'Prefabrik Ev', 'Köşk / Konak / Yalı',
       'Çiftlik Evi', 'Yalı Dairesi', 'Loft'], dtype=object)

In [6]:
df["sub_type"] = df["sub_type"].map({
    "Rezidans": "Резиденция (Жилой комплекс)",
    "Daire": "Квартира",
    "Villa": "Вилла",
    "Müstakil Ev": "Отдельный дом (Частный дом)",
    "Kooperatif": "Кооператив (Кооперативная квартира)",
    "Yazlık": "Летний дом (Дача)",
    "Komple Bina": "Целиком здание (Апарт-отель/Доходный дом)",
    "Prefabrik Ev": "Префабричный дом (Модульный дом)",
    "Köşk / Konak / Yalı": "Особняк / Конак / Ялы (Элитный особняк у моря)",
    "Çiftlik Evi": "Фермерский дом (Усадьба)",
    "Yalı Dairesi": "Квартира в ялы (Апартаменты у моря)",
    "Loft": "Лофт"
})

In [7]:
df["listing_type"].unique()

array([2, 1, 3], dtype=int64)

In [8]:
df["listing_type"] = df["listing_type"].map({
    1: "Продажа",
    2 : "Аренда",
    3 : "Неизвестно"
})

In [9]:
df["heating_type"].unique()

array(['Fancoil', 'Yok', 'Kalorifer (Doğalgaz)', 'Kalorifer (Kömür)',
       'Kombi (Elektrikli)', 'Klima', 'Kombi (Doğalgaz)',
       'Merkezi Sistem (Isı Payı Ölçer)', 'Merkezi Sistem',
       'Soba (Kömür)', 'Yerden Isıtma', 'Soba (Doğalgaz)',
       'Güneş Enerjisi', 'Kalorifer (Akaryakıt)', 'Jeotermal',
       'Kat Kaloriferi'], dtype=object)

In [10]:
df["heating_type"] = df["heating_type"].map({
    "Fancoil": "Фанкойл (система вентиляции/кондиционирования)",
    "Yok": "Нет",
    "Kalorifer (Doğalgaz)": "Калорифер (Природный газ)",
    "Kalorifer (Kömür)": "Калорифер (Уголь)",
    "Kombi (Elektrikli)": "Комби-котёл (Электрический)",
    "Klima": "Кондиционер",
    "Kombi (Doğalgaz)": "Комби-котёл (Природный газ)",
    "Merkezi Sistem (Isı Payı Ölçer)": "Центральное отопление (С тепловым счётчиком)",
    "Merkezi Sistem": "Центральное отопление",
    "Soba (Kömür)": "Печь (Уголь)",
    "Yerden Isıtma": "Тёплый пол",
    "Soba (Doğalgaz)": "Печь (Природный газ)",
    "Güneş Enerjisi": "Солнечная энергия",
    "Kalorifer (Akaryakıt)": "Калорифер (Жидкое топливо)",
    "Jeotermal": "Геотермальное отопление",
    "Kat Kaloriferi": "Этажный калорифер (локальная котельная на этаж)"
})

In [11]:
df["price_currency"].unique()

array(['TRY', 'GBP', 'EUR', 'USD', nan], dtype=object)

In [12]:
df["price_currency"] = df["price_currency"].map({
    "TRY": "TRY (Турецкая лира)",
    "GBP": "GBP (Фунт стерлингов)",
    "EUR": "EUR (Евро)",
    "USD": "USD (Доллар США)",
    float('nan'): "Неизвестно"
})

In [13]:
df.head().T

,0,1,2,3,4
id,1,2,3,4,5
type,Жилье,Жилье,Жилье,Жилье,Жилье
sub_type,Резиденция (Жилой комплекс),Квартира,Квартира,Резиденция (Жилой комплекс),Резиденция (Жилой комплекс)
start_date,12/10/18,02/13/19,10/09/18,09/10/18,12/10/18
end_date,01/09/19,02/27/19,11/08/18,10/10/18,01/09/19
listing_type,Аренда,Продажа,Продажа,Продажа,Продажа
tom,30,14,30,30,30
building_age,0,0,0,3,0
total_floor_count,21,21,1,21,21
floor_no,2,20,1,20,2
room_count,3,1,3,7,3
size,90.0,43.0,85.0,450.0,90.0
heating_type,Фанкойл (система вентиляции/кондиционирования),Фанкойл (система вентиляции/кондиционирования),Фанкойл (система вентиляции/кондиционирования),Фанкойл (система вентиляции/кондиционирования),Фанкойл (система вентиляции/кондиционирования)
price,8750.0,1225000.0,387500.0,81250000.0,3625000.0
price_currency,TRY (Турецкая лира),TRY (Турецкая лира),TRY (Турецкая лира),TRY (Турецкая лира),TRY (Турецкая лира)
city,İstanbul,İstanbul,Tekirdağ,İstanbul,İstanbul
district,Kartal,Kartal,Çorlu,Beşiktaş,Kartal
neighborhood,Kordonboyu,Kordonboyu,Reşadiye,Levent,Kordonboyu

In [14]:
df.to_csv("translated_data.csv", index=False)